test: &default

  # Credentials for REST APIs
  client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: dude_api1.hotmail.es
  password: WC89FAW4E6N5PEKA
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31ACwd6g7hhhBCeUn.ndSBp5HmqJIl
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: dude_api1@hotmail.es

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  mode: live
